
project_id = "joephviktsbxtkidveho"

[auth.email]
enable_confirmations = false

[functions.analyze-sports-video]
verify_jwt = true

[functions.share-sports-video]
verify_jwt = true

[functions.send-match-email]
verify_jwt = true

[functions.matchi-booking]
verify_jwt = true

