// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joephviktsbxtkidveho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZXBodmlrdHNieHRraWR2ZWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjc5NDIsImV4cCI6MjA2MDQwMzk0Mn0.26GJglrTqYiCK8v4yI3Xfm66vf9qcnMIme19BJ4QLwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);